-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")
--
--
-- -- Load project-local dap config if present
-- vim.api.nvim_create_autocmd("VimEnter", {
--   callback = function()
--     local cwd = vim.fn.getcwd()
--     local dap_file = cwd .. "/.nvim/dap.lua"
--     if vim.fn.filereadable(dap_file) == 1 then
--       dofile(dap_file)
--       print("Loaded project DAP config")
--     end
--   end,
-- })
